### ISSUE TITLE
Revive Notification 

### ISSUE THREAD

**Issue by TTVEscobarLadini** [FAXES/fax-revive#5]
For some odd reason the notification to revive myself show while I'm not dead

**Comment by Techdude404Gaming** [comment]
I also have this issue. Starts immediately upon loading into server and never goes away.

**Comment by alexius544** [comment]
I fixed this @Techdude404Gaming @TTVEscobarLadini, just waiting for @FAXES to merge. Check out [this ](https://github.com/alexius544/fax-revive) for now tho if you want a working version <3
