### ISSUE TITLE
Bypass broken.

### ISSUE THREAD

**Issue by Itz-Hyperz** [FAXES/fax-revive#7]
bypass roles system is broken :[

**Comment by Itz-Hyperz** [comment]
```
SCRIPT ERROR: @fax-revive/server.lua:30: attempt to index a nil value (field '?')
```

**Comment by FAXES** [comment]
Seems to be a couple issues with this resource. It's going to be remade in the future. So stay tuned for that if you'd like too as it is due for some changes.
